### ISSUE TITLE
<AP> RC500S: Disrupted Android APP in Hebrew Operating System

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/APP-Software-Issue#1]
Issue occurs when the operating system is in Hebrew:
- Disrupted APP 
- Files can't be downloaded to the phone.

**Comment by dod-pm1** [comment]
Got it, APP writter has being into this since last week.
Updated APP with new FW in June will solve this.
When is the strings coming?

**Comment by DOD-AP-Sales** [comment]
Offered via mail on June 6th, thanks.

**Comment by dod-pm1** [comment]
Got it, will combine with current strings manually and included in the update in late June.
Agree to close? or you prefer to leave this until APP release?

**Comment by DOD-AP-Sales** [comment]
Await confirmation till the APP release.
