### ISSUE TITLE
<AP> Include TH to DOD APP Strings  

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/APP-Software-Issue#3]
Offered the TH translation on May 31st.

**Comment by dod-pm1** [comment]
Recieved, will add to strings table for June's update

**Comment by dod-pm1** [comment]
Strings finished and sent to APP provider already.
They will test it out, both TH and HE prior to release the new version of APP this month to go with the new FW.
Agree to close?

**Comment by DOD-AP-Sales** [comment]
OK. thanks.
