### ISSUE TITLE
<AP> Camera Wi-Fi Settings 

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/APP-Software-Issue#7]
DOD DashCam iOS V2.0.7.4 is currently available on the App Store.
BUT customers cannot change their Wi-Fi password.
Originally it could be accessed via "Camera Wi-Fi Settings", but now there is no such an option.

**Comment by dod-pm1** [comment]
That will be open by our FW.
RD claimed that this version is the "mid-fix", which the main point is to release the IQ.
However, I have confirmed with APP supplier that this coding is already open on their side.

**Comment by DOD-AP-Sales** [comment]
New FW got it solved.
