### ISSUE TITLE
<AP> APP Compatibility with Google Pixel phone Android

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/APP-Software-Issue#8]
AU最近接獲散客通報使用RC500S 0703最新FW時還是不好用
不好用的點是使用APP不順
巧合的地方這兩位都是使用
Google Pixel phone Android version 7.1.2以上
客戶來信敘述"It is very difficult to get the Android App to connect to the device, I am only having success when manually resetting the device a couple of times."

**Comment by dod-pm1** [comment]
As discussed, APP provider still looking for cause, situation seems weird.
I will provide you a test version via SKYPE, see if it can solve this issue.

**Comment by DOD-AP-Sales** [comment]
Asked customer to "report" when crashed.
